{% set version = "3.3.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tractor.base
  version: {{ version|replace("-", "_") }}

source:
  fn: tractor.base_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tractor.base_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tractor.base/tractor.base_{{ version }}.tar.gz
  sha256: d2c3841114d21bc211d11f8d703ec74b888d9ff3ab9cef7331057aa0326fc244

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: mmand, loder, yaml, RNifti
requirements:
  host:
    - r-base
    - r-ore >=1.3.0
    - r-reportr
    - r-shades
    - r-nifti
  run:
    - r-base
    - r-ore >=1.3.0
    - r-reportr
    - r-shades
    - r-nifti

test:
  commands:
    - $R -e "library('tractor.base')"  # [not win]
    - "\"%R%\" -e \"library('tractor.base')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/tractor.base/index.html
  license: GPL-2
  summary: Functions for working with magnetic resonance images. Analyze, NIfTI-1, NIfTI-2 and
    MGH format images can be read and written; DICOM files can only be read.
  license_family: GPL2
extra:
   recipe-maintainers:
    - dpryan79
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
