{% set version = "3.3.5.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tractor.base
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tractor.base_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tractor.base/tractor.base_{{ version }}.tar.gz
  sha256: ec6d7891d1c68b3a3b713ef04ae487ecf53687479c574b422d859a78e1faab3b

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rnifti
    - r-ore >=1.3.0
    - r-reportr
    - r-shades
  run:
    - r-base
    - r-rnifti
    - r-ore >=1.3.0
    - r-reportr
    - r-shades

test:
  commands:
    - $R -e "library('tractor.base')"           # [not win]
    - "\"%R%\" -e \"library('tractor.base')\""  # [win]

about:
  home: http://www.tractor-mri.org.uk, https://github.com/tractor/tractor
  license: GPL-2.0-only
  summary: Functions for working with magnetic resonance images. Reading and writing of popular file formats (DICOM, Analyze, NIfTI-1, NIfTI-2, MGH); interactive and non-interactive visualisation; flexible image manipulation; metadata and sparse image handling.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - FrodePedersen
    - ArneKr
    - MathiasHaudgaard

# Package: tractor.base
# Version: 3.3.3.1
# Date: 2020-12-12
# Title: Read, Manipulate and Visualise Magnetic Resonance Images
# Author: Jon Clayden
# Maintainer: Jon Clayden <code@clayden.org>
# Imports: methods, ore (>= 1.3.0), reportr, shades, RNifti
# Suggests: mmand, loder, divest, jsonlite, yaml, testthat
# Enhances: oro.nifti
# Description: Functions for working with magnetic resonance images. Reading and writing of popular file formats (DICOM, Analyze, NIfTI-1, NIfTI-2, MGH); interactive and non-interactive visualisation; flexible image manipulation; metadata and sparse image handling.
# Encoding: UTF-8
# LazyLoad: yes
# LazyData: yes
# License: GPL-2
# URL: http://www.tractor-mri.org.uk, https://github.com/tractor/tractor
# BugReports: https://github.com/tractor/tractor/issues
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2020-12-12 23:10:37 UTC; jon
# Repository: CRAN
# Date/Publication: 2020-12-13 01:00:02 UTC
