travis:
  secure:
    BINSTAR_TOKEN: aYzehyuIn+4/sVMXulS6DoN4UPuQUTcRh39RRLDJwAZY4zf6T89tMydpuadwRr9sSKzywHNfhdIb0iaykiLabMhDEyHASJ+P9UvdVa7pOaZWXtPxbnR06sR6w8evwDNt5v8i3NPx8oCPzZowVOvEH/n1GyfsCh3FO1M0xyrk+W8CWrV3HwNAJH3Reorq99SNfB2mulflAeyy1a+281mksf7/fGBSLFX+zYtDmEPY2va9N5jzfHjmg57SklvnG9N2F4cICu2v3BdYqlu3mSAblkB5KYsnJNplFGzIRBEjvrcXNM5PJAalxmf1WMAxPR6VASFODlaZolbTuA+OGYhk1oKhntdNCJoWeEvXGGznhpLOSWSacsCmTYkG8VhTVSNJpO7502t5yOQ4OR2C9KMtrEkrhHDJ2dYVhBVdwdNTysu7ilMs88NfEcZaZ/SwxbzP4nsTBgdT+76TJNCmTS3qmZLBVr34/ZXAR6gNvMdp3HUc+3aMYtd7Y1Em/WdHzVQH0izU8xmWSKcbomWHQ8RRkobMgwOTQw6FExYEXuYdNClPYucGFUzDRE0+hLbo3uqHEJyunL0BgTpd9ROKEfXGZpe/e/mlQLvpDgb0vkElIXnPVV/1PHNWbJdZ4ncbyFBXW9GtYQL/nrLVGMtThpW+KpenltHO6FWbtBoNWNSdKNw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
