appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: r3UT2hVzpOTqXR4/HPSAqqafZ9yZuRUBdbKvVZzhXAkKPismegqG/thb/gdbNNQtxEd8yW4Ti+qoOW/aMFb43iK3RHQaI192CWVl7B/6wGAXIuXJYx60cV1dOaJJXbPrqUIg6aC5nOkOBcT146m2K8R7juDKoOkgZxpLhqGVqlE41gu8HD8Tc06uEpxzz4OB6KExmUAqmYj7TTlPsvFPhrq78oOkJsLktd0YRB7jVwAcsgHM7ANqiYgEp/KD6JX3+FWoVLwBB0sQ5q/LNqe9srY66bXgTQwWncDTghBn+o0B1P+P8V4eoLWb4jYWiJo+LvIPYufyglZ0VtmjqIHEyxkpfksRqbPA4QQaNaGa0Wgf+AdYCQJaXn+uyN3Ypby+Fu5S3FWd2gA+LeerkRYT4jo+9aYIn9ZjEDIDCfFRrjYzZJPA5CbV+vkIK7Vwq/JYBxEBz0c0eRRoK488qFYw5YeQXanRUW6MwXAzbo/oYzPA393kJAGpCNXuEaRft6Otv+j3dfg0u6kQSLAj64OSeE9UB5LlndT8hJNFvFxkP96B8Pgi6iKJ8efhEMKIfxRcLrePKu1UErLlPmihN5/NigiCoD+o16pDnPqBMpS6bPI1P1kKhZcXk2Pq/UIw0tBbaPcXtO0D7jlK1phvi6nBEZtQppVblloLFIJQ8m4fCs8=}
